

###
POST http://localhost:8080/appointment HTTP/1.1
content-type: application/json


{
    "userId": "5de63dc4-7a47-4e04-a978-05ad25c0dfa5",
    "appointmentDateId": "9c83377f-9760-444e-b99e-342d20476e31"
}

###
POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
    "email": "seniorfresh@gmail.com",
    "password": "ontfdfdf"
}

